// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPvA9GTJ5Hau0nXGl68yc0BM2Ag-J711k',
    appId: '1:622909271424:web:69569a3d09d0763509a565',
    messagingSenderId: '622909271424',
    projectId: 'family-tree-28046',
    authDomain: 'family-tree-28046.firebaseapp.com',
    databaseURL: 'https://family-tree-28046-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-tree-28046.firebasestorage.app',
    measurementId: 'G-4BWVCQ2G4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChEK7tfJgWKPFG4msOZfGYqUeUjJEic2E',
    appId: '1:622909271424:android:e36ef97fea9d18e409a565',
    messagingSenderId: '622909271424',
    projectId: 'family-tree-28046',
    databaseURL: 'https://family-tree-28046-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-tree-28046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsIng8muQ6p9DXalk3ClLk8H6YluI6c-A',
    appId: '1:622909271424:ios:5804cf2ef2b6876909a565',
    messagingSenderId: '622909271424',
    projectId: 'family-tree-28046',
    databaseURL: 'https://family-tree-28046-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-tree-28046.firebasestorage.app',
    iosBundleId: 'com.example.finalTestFamilyTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsIng8muQ6p9DXalk3ClLk8H6YluI6c-A',
    appId: '1:622909271424:ios:5804cf2ef2b6876909a565',
    messagingSenderId: '622909271424',
    projectId: 'family-tree-28046',
    databaseURL: 'https://family-tree-28046-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-tree-28046.firebasestorage.app',
    iosBundleId: 'com.example.finalTestFamilyTree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPvA9GTJ5Hau0nXGl68yc0BM2Ag-J711k',
    appId: '1:622909271424:web:784d2562f985e7e309a565',
    messagingSenderId: '622909271424',
    projectId: 'family-tree-28046',
    authDomain: 'family-tree-28046.firebaseapp.com',
    databaseURL: 'https://family-tree-28046-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'family-tree-28046.firebasestorage.app',
    measurementId: 'G-HHS7TXJ3B5',
  );
}
